name: geohpem
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.23
  - pyside6>=6.6
  - meshio>=5.3
  - pygmsh>=7.1
  - gmsh>=4.11
  - pyvista>=0.43
  - pyvistaqt>=0.11
  - pip
  - pip:
      - jsonschema>=4

